# Generated by Django 5.1.5 on 2025-02-06 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPublica',
            fields=[
                ('idAre', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAre', models.CharField(max_length=250)),
                ('ubicacionAre', models.CharField(max_length=250)),
                ('estadoAre', models.CharField(max_length=250)),
                ('fecha_creacionAre', models.DateField()),
                ('foto', models.FileField(blank=True, null=True, upload_to='areaPublica')),
            ],
        ),
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('idCon', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCon', models.CharField(max_length=250)),
                ('telefonoCon', models.CharField(max_length=10)),
                ('emailCon', models.EmailField(max_length=254)),
                ('especialidadCon', models.CharField(max_length=250)),
                ('experienciaCon', models.CharField(max_length=250)),
                ('foto', models.FileField(blank=True, null=True, upload_to='contratista')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('idMat', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMat', models.CharField(max_length=250)),
                ('tipoMat', models.CharField(max_length=250)),
                ('unidadMat', models.CharField(max_length=250)),
                ('costoMat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidadMat', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('idPro', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePro', models.CharField(max_length=250)),
                ('fecha_inicioPro', models.DateField()),
                ('fecha_finPro', models.DateField()),
                ('estadoPro', models.CharField(max_length=250)),
                ('presupuestoPro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.FileField(blank=True, null=True, upload_to='proyecto')),
                ('area_publica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='Espacios.areapublica')),
            ],
        ),
    ]
